type IriString = `${'http' | 'https'}://${string}`;
type Property = IriString; // eslint-disable-line
type Class = IriString; // eslint-disable-line
type Datatype = IriString; // eslint-disable-line
type OwlClass = IriString; // eslint-disable-line
type OwlObjectProperty = IriString; // eslint-disable-line
type OwlDatatypeProperty = IriString; // eslint-disable-line
type HydraResource = IriString; // eslint-disable-line
type HydraClass = IriString; // eslint-disable-line
type HydraLink = IriString; // eslint-disable-line
type HydraTemplatedLink = IriString; // eslint-disable-line
type HydraVariableRepresentation = IriString; // eslint-disable-line
type OtherIndividual = IriString; // eslint-disable-line

/**
 * Entry
 * 
 * 
 *
 * http://purl.org/ldht/Entry
 */
export const Entry: OwlClass = 'http://purl.org/ldht/Entry';

/**
 * Collection
 * 
 * A ldht:Collection is a tree collection.
 *
 * http://purl.org/ldht/Collection
 */
export const Collection: OwlClass = 'http://purl.org/ldht/Collection';

/**
 * Node
 * 
 * A ldht:Node is a node in a distributed hash tree that may contain relations to other nodes in the distributed hash tree.
 *
 * http://purl.org/ldht/Node
 */
export const Node: OwlClass = 'http://purl.org/ldht/Node';

/**
 * Add node action
 * 
 * The act of indicating to a node that a new node has joined the network.
 *
 * http://purl.org/ldht/AddNodeAction
 */
export const AddNodeAction: OwlClass = 'http://purl.org/ldht/AddNodeAction';

/**
 * Ping action
 * 
 * The act of pinging a node to request if it is still active and responding to actions.
 *
 * http://purl.org/ldht/PingAction
 */
export const PingAction: OwlClass = 'http://purl.org/ldht/PingAction';

/**
 * Remove node action
 * 
 * The act of indicating to a node that another node is removed in the network.
 *
 * http://purl.org/ldht/RemoveNodeAction
 */
export const RemoveNodeAction: OwlClass = 'http://purl.org/ldht/RemoveNodeAction';

/**
 * Store value action
 * 
 * The act of storing a value in a node.
 *
 * http://purl.org/ldht/StoreValueAction
 */
export const StoreValueAction: OwlClass = 'http://purl.org/ldht/StoreValueAction';

/**
 * Hashing function
 * 
 * The hashing function describes how input data is transformed to a value
 *
 * http://purl.org/ldht/hashFunction
 */
export const hashFunction: OwlObjectProperty = 'http://purl.org/ldht/hashFunction';

/**
 * key
 * 
 * 
 *
 * http://purl.org/ldht/key
 */
export const key: OwlObjectProperty = 'http://purl.org/ldht/key';

/**
 * Nodes collection
 * 
 * Indicates the collection of nodes for a particular linked data hash table
 *
 * http://purl.org/ldht/nodes
 */
export const nodes: OwlObjectProperty = 'http://purl.org/ldht/nodes';

/**
 * value
 * 
 * 
 *
 * http://purl.org/ldht/value
 */
export const value: OwlObjectProperty = 'http://purl.org/ldht/value';

/**
 * node identifier
 * 
 * The node identifier is a number generated by using the hash algorithm of the network.
 *
 * http://purl.org/ldht/nodeID
 */
export const nodeID: OwlDatatypeProperty = 'http://purl.org/ldht/nodeID';

/**
 * timeout
 * 
 * The timeout is the time in milliseconds that a node will wait for a response from another node.
 *
 * http://purl.org/ldht/timeout
 */
export const timeout: OwlDatatypeProperty = 'http://purl.org/ldht/timeout';

export const _BASE: IriString = 'http://purl.org/ldht/';
export const _PREFIX: string = 'ldht';